# -*- coding: utf-8 -*-
"""Merging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-lExZHfEp3kgDrOHMwOdmxUkrwjPfNn

# Explore Data

## Import Files and Packages
"""

import sys
import pandas as pd
from core import create_charai_data
import logging
from scipy.spatial.distance import cdist
import numpy as np

harvest_file_name_total = "./Data/CookHandHarvest_HY1999-HY2016_P3A3_20241029(in).csv"
logger = logging.getLogger("charai")
coords = []
tiff_file_path = "./tiff.tif"


"""## Harvest"""

harvest = pd.read_csv(harvest_file_name_total)

# drop any columns that are more than 1000 missing values
harvest = harvest.loc[:, harvest.isna().sum() <= 1000]

# Drop unnecessary "SampleID" Column
harvest.drop(columns=["SampleID"], inplace=True)

# Drop rows with missing "Crop" or "GrainYieldAirDry" Values
harvest = harvest.dropna()
harvest.isna().sum()

# Drop columns: QCCoverage, QCFlags, CropExists
harvest.drop(columns=["QCCoverage", "QCFlags", "CropExists", "ID2", "HarvestYear"], inplace=True)

harvest.head()

output_path = "/content/drive/MyDrive/Colab Notebooks/Capstone/Data/harvest_combined.csv"
harvest.to_csv(output_path, index=False)
print(f"Harvest dataframe saved to: {output_path}")

harvest.shape

# Total different types of crops
harvest["Crop"].nunique()

harvest["Crop"].unique()

"""## CharAI Cook"""

charai = create_charai_data(logger, coords, tiff_file_path)

charai.drop(columns=["ID2", "FieldName"], inplace=True)

charai.head()

charai.shape

# Create coordinate arrays for harvest and charai
harvest_coords = harvest[['Latitude', 'Longitude']].values
charai_coords = charai[['Latitude', 'Longitude']].values

# Calculate all pairwise distances
distances = cdist(harvest_coords, charai_coords, metric='euclidean')

# Find the index of the closest charai point for each harvest point
closest_charai_indices = np.argmin(distances, axis=1);

# Select the corresponding charai rows
# Using .iloc to select rows by integer index
closest_charai_data = charai.iloc[closest_charai_indices]

# Reset index of harvest to ensure clean concatenation
harvest_reset = harvest.reset_index(drop=True)

# Select relevant columns from closest_charai_data to merge.
# We want all columns from charai EXCEPT FieldName, Latitude, Longitude.
# We already have Latitude and Longitude in harvest. FieldName is an identifier.
charai_cols_to_merge = [col for col in charai.columns if col not in ['FieldName', 'Latitude', 'Longitude']]
charai_attributes_to_add = closest_charai_data[charai_cols_to_merge].reset_index(drop=True)

# Concatenate the harvest DataFrame with the selected charai attributes
harvest = pd.concat([harvest_reset, charai_attributes_to_add], axis=1)

print(harvest.head())

harvest.head()

harvest.shape

