# -*- coding: utf-8 -*-
"""CharAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w22z0vTsDfGuoWk1xAQGEhPt2CsblzOj

# Cook Data Exploration

## Imports
"""

import sys
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from google.colab import drive

import keras # please install the keras package first
import keras.layers as layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import r2_score, mean_squared_error

"""## Data Import and Combine"""

# Import files

crop_file_name = ""
terrain_file_name = ""

if 'google.colab' in sys.modules:
  drive.mount('/content/drive')
  crop_file_name = "/content/drive/MyDrive/Colab Notebooks/Capstone/Data/CookHandHarvest_HY1999-HY2016_P3A3_20241029(in).csv"
  terrain_file_name = "/content/drive/MyDrive/Colab Notebooks/Capstone/Data/CookTerrainAttributes10m2_P3A1_20210119.csv"
else:
  crop_file_name = "./Data/CookHandHarvest_HY1999-HY2016_P3A3_20241029(in).csv"
  terrain_file_name = "./Data/CookTerrainAttributes10m2_P3A1_20210119.csv"

print(crop_file_name)
print(terrain_file_name)

"""### Crop"""

crop = pd.read_csv(crop_file_name)

shape_before = crop.shape
print(shape_before)

# drop any columns that are more than 1000 missing values
crop = crop.loc[:, crop.isna().sum() <= 1000]

# Drop unnecessary "SampleID" Column
crop.drop(columns=["SampleID"], inplace=True)

# Drop rows with missing "Crop" or "GrainYieldAirDry" Values
crop = crop.dropna()
crop.isna().sum()

shape_after = crop.shape
print(shape_after)

print(f'Dropped Column amount: {shape_before[1] - shape_after[1]}')
print(f'Dropped Row amount: {shape_before[0] - shape_after[0]}')

"""### Terrain"""

terrain = pd.read_csv(terrain_file_name)

terrain.head()

shape_before = terrain.shape
print(shape_before)

terrain.isna().sum()

shape_after = terrain.shape
print(shape_after)

print(f'Dropped Column amount: {shape_before[1] - shape_after[1]}')
print(f'Dropped Row amount: {shape_before[0] - shape_after[0]}')

"""### Combine"""

print(f"crop['ID2'].nunique(): {crop['ID2'].nunique()}")
print(f"terrain['ID2'].nunique(): {terrain['ID2'].nunique()}")

"""`crop` only contains data from *Cook East* location but `terrain` contains data from *Cook East* and *Cook West*"""

print(f"terrain['Longitude'].iloc[0]: {terrain['Longitude'].iloc[0]}")
print(f"crop['Longitude'].iloc[0]: {crop['Longitude'].iloc[0]}")

# Combine "crop" and "terrain" dataframes on "ID2" column
combined = pd.merge(crop, terrain, on=["ID2"], how="inner")

"""**Note:** I tried to merge based off Longitude and Latitude but the "terrain" dataframes values are more precise so the values do not match (see cell above). This is why we merge based on "ID2" primarily. Later we should return to this and ensure that the ID2's Longitude and Latitude match."""

combined.shape

combined.isna().sum()

"""## Data Exploration"""

# Drop "QCCoverage" column becauuse it is NaN

combined.drop(columns=["QCCoverage"], inplace=True)

# Remove the following to simplify the dataset
columns_to_remove = [
    "ID2",
    "HarvestYear",
    "Longitude_x",
    "Latitude_x",
    "Longitude_y",
    "Latitude_y",
    "FieldName",

]
combined.drop(columns=columns_to_remove, inplace=True)

print(combined.columns.tolist())

combined.shape

combined["GrainYieldAirDry"].max()

combined["GrainYieldAirDry"].min()

print(combined.columns.tolist())

corr = combined.select_dtypes(include="number").corr()

sns.heatmap(corr, cmap="coolwarm")
plt.show()

"""## Data Processing

### Encoding Categorical Values
"""

print(combined.select_dtypes(include=["object", "category"]).columns.tolist())

le = LabelEncoder()
combined["Crop"] = le.fit_transform(combined["Crop"].astype(str))

combined["Crop"].value_counts()

print(combined.select_dtypes(include=["object", "category"]).columns.tolist())

"""### Split"""

target_column = "GrainYieldAirDry"

X = combined.drop(columns=[target_column])
y = combined[target_column]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""### Scale"""

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""## Model

X_train, X_test, y_train, y_test
"""

print(f'X_train.shape: {X_train.shape}')
print(f'X_train.shape: {X_test.shape}')
print(f'X_train.shape: {y_train.shape}')
print(f'X_train.shape: {y_test.shape}')

def Create_Model(input_dim):
    model = keras.models.Sequential()

    # Input layer
    model.add(keras.layers.Input(shape=(input_dim,)))

    # Hidden layers
    model.add(keras.layers.Dense(
        units=128,
        activation='relu',
        kernel_initializer='he_normal'
    ))
    model.add(keras.layers.Dense(
        units=64,
        activation='relu',
        kernel_initializer='he_normal'
    ))
    model.add(keras.layers.Dense(
        units=32,
        activation='relu',
        kernel_initializer='he_normal'
    ))
    # Optional regularization (uncomment if you see overfitting)
    # model.add(keras.layers.Dropout(0.2))

    # Output layer for regression (one continuous value)
    model.add(keras.layers.Dense(
        units=1,
        activation='linear',          # << no activation = regression
        kernel_initializer='glorot_uniform'
    ))

    # Compile for regression
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=1e-3),
        loss='mse',                   # mean squared error
        metrics=['mae']               # mean absolute error
    )

    return model


# Create model with correct input dimension
input_dim = X_train.shape[1]
model = Create_Model(input_dim)

model.summary()

# Early stopping (you already imported EarlyStopping)
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

# Train
history = model.fit(
    X_train, y_train,
    validation_split=0.2,   # use part of training data for validation
    epochs=200,
    batch_size=32,
    callbacks=[early_stop],
    verbose=0                # change to 1 to see progress
)

# Evaluate on test set
test_loss, test_mae = model.evaluate(X_test, y_test, verbose=0)

# Predictions for extra metrics
y_pred = model.predict(X_test).flatten()

mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print(f"Test MSE:  {mse:.4f}")
print(f"Test RMSE: {rmse:.4f}")
print(f"Test MAE:  {test_mae:.4f}")
print(f"Test R^2:  {r2:.4f}")

model.save("/content/drive/MyDrive/Colab Notebooks/Capstone/yield_model.keras")

# model = keras.models.load_model("yield_model.keras")
# model.summary()