# Generated by Django 5.2.8 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_prescriptionmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="prescription_map_file",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="field",
            name="prescription_map_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
