# Generated by Django 5.2.8 on 2026-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_field_prescription_status_and_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="custom_crop",
        ),
        migrations.AlterField(
            model_name="field",
            name="crop_type",
            field=models.CharField(
                choices=[
                    ("SW", "Spring Wheat"),
                    ("SB", "Spring Barley"),
                    ("SC", "Spring Canola"),
                    ("SP", "Spring Pea"),
                    ("WW", "Winter Wheat"),
                    ("WB", "Winter Barley"),
                    ("WP", "Winter Pea"),
                    ("WC", "Winter Canola"),
                    ("WL", "Winter Lentil"),
                    ("AL", "Alfalfa"),
                    ("WT", "Winter Triticale"),
                    ("GB", "Grain Buckwheat"),
                ],
                max_length=2,
            ),
        ),
    ]
