# Generated by Django 5.2.8 on 2026-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_biochar_inputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="field",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="field",
            name="crop_type",
            field=models.CharField(
                choices=[
                    ("AL", "Alfalfa"),
                    ("GB", "Grain Buckwheat"),
                    ("SB", "Spring Barley"),
                    ("SC", "Spring Canola"),
                    ("SP", "Spring Pea"),
                    ("SW", "Spring Wheat"),
                    ("WB", "Winter Barley"),
                    ("WC", "Winter Canola"),
                    ("WL", "Winter Lentil"),
                    ("WP", "Winter Pea"),
                    ("WT", "Winter Triticale"),
                    ("WW", "Winter Wheat"),
                ],
                max_length=2,
            ),
        ),
    ]
